version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci # Faster & cleaner for CI/CD
  build:
    commands:
      - npm run build
      - ls -lah dist || echo "Build failed, dist folder missing"
  post_build:
    commands:
      - echo "✅ Build completed successfully"
      # Retrieve the SSH key from AWS Secrets Manager
      - aws secretsmanager get-secret-value --secret-id my-ec2-key2 --query SecretString --output text > /tmp/ec2-key.pem
      - chmod 400 /tmp/ec2-key.pem
      # Deploy the build artifacts to EC2
      - echo "Deploying build artifacts to EC2"
      - scp -o StrictHostKeyChecking=no -i /tmp/ec2-key.pem -r dist/* ec2-user@3.95.38.137:/home/ec2-user/app
      - ssh -o StrictHostKeyChecking=no -i /tmp/ec2-key.pem ec2-user@3.95.38.137 "cd /home/ec2-user/app && pm2 restart app || pm2 start 'serve -s . -l 3000' --name app"

artifacts:
  files:
    - dist/**/* # The build output
