name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ AKIAWNHTHK35XD35JW7E }}
          aws_secret_key: ${{ secrets.7PHWAIQnV/7D77IQa5kQ7giwdhiaarhtkStNpXrf }}
          application_name: daytrading-anallytics
          environment_name: Daytrading-anallytics-env
          version_label: ${{ github.sha }}
          region: <region> # e.g., us-east-1
          deployment_package: ./